Sleep before sending message

diff --git a/build b/build
--- a/build
+++ b/build
@@ -11,36 +11,45 @@ export CCACHESIZE="20G"
 export LUNCHCOMMAND="lunch corvus_mido-user"
 export BUILDCOMMAND="make corvus"
 #--------------------------EDIT UPTO HERE--------------------------------
+sudo apt install jq -y 1>/dev/null
 
 # Functions And imp stuff
-sudo apt install jq -y
-function tg() {
+function TG() {
     TEXT1="$1"
-    M_ID=$(curl -s "https://api.telegram.org/bot${BOTAPI}/sendmessage" --data "text=$1&chat_id=${ID}" | jq .result.message_id) 1>/dev/null
+    M_ID=$(curl -s "https://api.telegram.org/bot${BOTAPI}/sendmessage" \
+        -d "text=$1&chat_id=${ID}" \
+        -d "disable_web_page_preview=true" \
+        -d "parse_mode=html" | jq .result.message_id) 1>/dev/null
 }
-function tgedit() {
+function TGEDIT() {
     TEXT2="$2"
-    curl -s -X POST https://api.telegram.org/bot"${BOTAPI}"/editMessageText -d chat_id="$ID" -d message_id="$1" -d text="$TEXT2" -d silent=true | jq . 1>/dev/null
+    curl -s -X POST https://api.telegram.org/bot"${BOTAPI}"/editMessageText \
+        -d chat_id="$ID" \
+        -d message_id="$1" \
+        -d text="$TEXT2" \
+        -d silent=true | jq . 1>/dev/null
 }
-function tgdoc() {
-    curl -F chat_id="${ID}" -F document=@"$1" -F caption="$2" https://api.telegram.org/bot"${BOTAPI}"/sendDocument >/dev/null
+function TGDOC() {
+    curl -F chat_id="${ID}" \
+        -F document=@"$1" \
+        -F caption="$2" https://api.telegram.org/bot"${BOTAPI}"/sendDocument >/dev/null
 }
-function del() {
+function DEL() {
     RESULT=$(curl -sf --data-binary @"${1:--}" https://del.dog/documents) || {
-        echo "ERROR: failed to post document" >&2
+        echo "DEL-ERROR" >&2
         return 1
     }
     KEY=$(printf "%s\n" "${RESULT}" | cut -d '"' -f6)
     echo "https://del.dog/${KEY}"
 }
-function com() {
+function COM() {
     tar --use-compress-program="pigz -k -$2 " -cf "$1".tar.gz "$1"
 }
 function T1() {
     date +"%I:%M%p"
 }
-function trim() {
-    grep -iE 'crash|error|fail|fatal|failed|missing' "$1" &>"Trim-$1"
+function TRIM() {
+    grep -iE 'crash|avc|error|fail|fatal|failed|missing' "$1" &>"Trim-$1"
 }
 
 # Rclone
@@ -49,89 +58,87 @@ echo "$rclone_config" >~/.config/rclone/rclone.conf
 
 # Env Variables
 rm -rf ./*.txt* ./*.md*
-export ERROR_LOG1="ErrorLog.txt"
 export TZ="Asia/Kolkata"
 export NL=$'\n'
 
 # Ci stats
 curl https://raw.githubusercontent.com/ramdibaaz/aosp-builder/main/extra.sh >>extra.sh && chmod +x ./extra.sh && bash extra.sh
-tgdoc "stats.md" "New build starts"
+TGDOC "stats.md" "New build starts"
 
 # Ccache
 export USE_CCACHE=1
 export CCACHE_DIR="/tmp/ccache"
 export CCACHE_EXEC="$(which ccache)"
+export CCACHE_COMPILERCHECK="none"
 ccache -M "$CCACHESIZE"
 ccache -o compression=true
-tg "$(ccache -s)"
+TG "$(ccache -s)"
 export B2="$M_ID"
 
 # Build Info notification
-tg "$(date)""$NL""IP:$(curl ipinfo.io/ip) By $USER""$NL""Type:$BUILD_TYPE Metalava:$METALAVA""$NL""ccache:$CCACHESIZE cores:$(nproc)""$NL""+++++++++++++++++++++"
+TG "$(date)""$NL""IP:$(curl ipinfo.io/ip) By $USER""$NL""Type:$BUILD_TYPE Metalava:$METALAVA""$NL""ccache:$CCACHESIZE cores:$(nproc)""$NL""+++++++++++++++++++++"
 export INFO="$M_ID"
 
 # Before build Steps
 source ./build/envsetup.sh && eval "$LUNCHCOMMAND"
-tgedit "$INFO" "$TEXT1""$NL""$(T1):Env Setup And Lunch"
-export SELINUX_IGNORE_NEVERALLOWS=true
+TGEDIT "$INFO" "$TEXT1""$NL""$(T1):Env Setup And Lunch"
 
 # Make Metalava Seperately
 if [[ "$METALAVA" = "true" ]]; then
-    tgedit "$INFO" "$TEXT2""$NL""$(T1):Metalava Build Started"
+    TGEDIT "$INFO" "$TEXT2""$NL""$(T1):Metalava Build Started"
     export WITHOUT_CHECK_API=true
     make api-stubs-docs || echo SKIPPING
-    make hiddenapi-lists-docs || echo SKIPPING
     make system-api-stubs-docs || echo SKIPPING
     make test-api-stubs-docs || echo SKIPPING
-    tgedit "$INFO" "$TEXT2""$NL""$(T1):Metalava Build Done"
+    TGEDIT "$INFO" "$TEXT2""$NL""$(T1):Metalava Build Done"
 fi
 
 # Final Build Start's Here
-tg "BUILD%" && export B3="$M_ID"
-eval "$BUILDCOMMAND" | tee "${ERROR_LOG1}" &
+TG "BUILD%" && export B3="$M_ID"
+eval "$BUILDCOMMAND" | tee ErrorLog.txt &
 sleep 60
 export END="$(date +"%I:%M%p" -d "$(date) + 83 minute")"
-tgedit "$INFO" "$TEXT2""$NL""$(T1):Main Build upto $END"
+TGEDIT "$INFO" "$TEXT2""$NL""$(T1):Main Build upto $END"
 
 # Build %'age and kill in 85m if build type is ccache
 if [[ "$BUILD_TYPE" = "ccache" ]]; then
     while test ! -z "$(pidof soong_ui)"; do
-        sleep 120
-        BUILD_STATS=$(tail <"${ERROR_LOG1}" -n 1 | awk '{ print $2 }')
-        tgedit "$B3" "$(T1)=$BUILD_STATS" && tgedit "$B2" "echo $(ccache -s)"
         if [[ "$(date +"%I:%M%p")" = "$END" ]]; then
             break
         fi
+        sleep 120
+        BUILD_STATS=$(tail <"ErrorLog.txt" -n 1 | awk '{ print $2 }')
+        TGEDIT "$B3" "$(T1)=$BUILD_STATS" && TGEDIT "$B2" "$(ccache -s)"
     done
     kill %1
-    tgedit "$INFO" "$TEXT2""$NL""$(T1):Killed FOR CCACHE UPLOAD"
+    TGEDIT "$INFO" "$TEXT2""$NL""$(T1):Killed FOR CCACHE UPLOAD"
 else
     while test ! -z "$(pidof soong_ui)"; do
         sleep 120
-        BUILD_STATS=$(tail <"${ERROR_LOG1}" -n 1 | awk '{ print $2 }')
-        tgedit "$B3" "$(T1)=$BUILD_STATS" && tgedit "$B2" "echo $(ccache -s)"
+        BUILD_STATS=$(tail <"ErrorLog.txt" -n 1 | awk '{ print $2 }')
+        TGEDIT "$B3" "$(T1)=$BUILD_STATS" && TGEDIT "$B2" "$(ccache -s)"
     done
 fi
 
 # Send logs or exit if no log found
 for B4 in *txt; do
     if [ -e "$B4" ]; then
-        trim "$B4"
-        tgdoc "$B4" "$(del "$B6")"
-        tgdoc "Trim-$B4" "$(del Trim-"$B6")"
+        TRIM "$B4"
+        TGDOC "$B4" "$(DEL "$B4")"
+        TGDOC "Trim-$B4" "$(DEL Trim-"$B4")"
     else
         break
     fi
 done
-tgdoc "./out/*log" "out/*log"
+TGDOC "./out/*log" "$(DEL ./out/*log)"
 
 # Upload Rom If Zip Found
 if ls /tmp/rom/out/target/product/mido/*zip 1>/dev/null 2>&1; then
     for LOOP in /tmp/rom/out/target/product/mido/*zip; do
         if [ -e "$LOOP" ]; then
             rclone copy "$LOOP" GDUP:ROM/ZIP
-            tgedit "$INFO" "$TEXT2""$NL""$(T1):Rom Uploaded"
-            tg "ROM URL:-https://rom.jrchintu.ga/0:/ZIP/$LOOP"
+            TGEDIT "$INFO" "$TEXT2""$NL""$(T1):Rom Uploaded"
+            TG "ROM URL:-https://rom.jrchintu.ga/0:/ZIP/$LOOP"
         else
             break
         fi
@@ -140,20 +147,20 @@ else
     tmate -S /tmp/tmate.sock new-session -d &&
         tmate -S /tmp/tmate.sock wait tmate-ready &&
         SENDSHELL=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}') &&
-        tgedit "$INFO" "$TEXT2""$NL""$(T1):Build Failed OR Zip Not Found" &&
-        tg "$SENDSHELL""$NL""Failed or it's ccache build""$NL""Use Tmate for 30min"
+        TGEDIT "$INFO" "$TEXT2""$NL""$(T1):Build Failed OR Zip Not Found" &&
+        TG "$SENDSHELL"
 fi
 
 # Upload ccache
 if [[ "$BUILD_TYPE" = "ccache" ]]; then
     cd /tmp || exit
-    tgedit "$INFO" "$TEXT2""$NL""$(T1):Uploading ccache"
-    com ccache 1
+    TGEDIT "$INFO" "$TEXT2""$NL""$(T1):Uploading ccache"
+    COM ccache 1
     rclone copy ccache.tar.gz GDUP:ROM/CCACHE
-    tgedit "$INFO" "$TEXT2""$NL""$(T1):Ccache Uploaded"
+    TGEDIT "$INFO" "$TEXT2""$NL""$(T1):Ccache Uploaded"
     cd /tmp/rom || exit
 fi
 
-# Sleep while tmate is running
-tgedit "$INFO" "$TEXT2""$NL""$(T1):STOPPED ALL FOR 30 MIN"
-sleep 30m
+# sleep while tmate is running
+TGEDIT "$INFO" "$TEXT2""$NL""$(T1):STOPPED ALL UPTO $END"
+sleep 120m
